//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_420_Sochnev_Renat_Agzyamovich.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TournamentDB_420_Sochnev_Renat_AgzyamovichEntities : DbContext
    {
        public TournamentDB_420_Sochnev_Renat_AgzyamovichEntities()
            : base("name=TournamentDB_420_Sochnev_Renat_AgzyamovichEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Format> Format { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<Organizer> Organizer { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<Tournament> Tournament { get; set; }
        public virtual DbSet<TournamentRegistration> TournamentRegistration { get; set; }
    }
}
