//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_420_Sochnev_Renat_Agzyamovich.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentRegistration
    {
        public int Id { get; set; }
        public Nullable<int> IdTournament { get; set; }
        public Nullable<int> IdMember { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Status Status { get; set; }
        public virtual Team Team { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
